//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Settings/InputControls/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""MouseKeyboard"",
            ""id"": ""1f3344f5-c7e6-425c-8a07-88968979f91e"",
            ""actions"": [
                {
                    ""name"": ""LeftButtonMousePress"",
                    ""type"": ""Button"",
                    ""id"": ""9b7fa326-f251-4d2c-93d7-3adb18fc19e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46fb56e5-1f7e-4432-bb6e-622a31fd59f5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftButtonMousePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TochScreen"",
            ""id"": ""2d37f190-5a7a-40ef-b22b-0bd97d1a301b"",
            ""actions"": [
                {
                    ""name"": ""SingleTouch"",
                    ""type"": ""Value"",
                    ""id"": ""8ce98c89-647e-4080-b3a2-4711bb4f9d01"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MultiTouch"",
                    ""type"": ""Button"",
                    ""id"": ""423e45b5-a541-4a58-a8ba-4233e4220b30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ca53541d-e9c8-4c84-bbe7-d0572b6620fc"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SingleTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a9ae8bb-208a-4662-87a5-b9f2a5c37a6d"",
                    ""path"": ""<Touchscreen>/touch*/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MultiTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MouseKeyboard
        m_MouseKeyboard = asset.FindActionMap("MouseKeyboard", throwIfNotFound: true);
        m_MouseKeyboard_LeftButtonMousePress = m_MouseKeyboard.FindAction("LeftButtonMousePress", throwIfNotFound: true);
        // TochScreen
        m_TochScreen = asset.FindActionMap("TochScreen", throwIfNotFound: true);
        m_TochScreen_SingleTouch = m_TochScreen.FindAction("SingleTouch", throwIfNotFound: true);
        m_TochScreen_MultiTouch = m_TochScreen.FindAction("MultiTouch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MouseKeyboard
    private readonly InputActionMap m_MouseKeyboard;
    private IMouseKeyboardActions m_MouseKeyboardActionsCallbackInterface;
    private readonly InputAction m_MouseKeyboard_LeftButtonMousePress;
    public struct MouseKeyboardActions
    {
        private @InputControls m_Wrapper;
        public MouseKeyboardActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftButtonMousePress => m_Wrapper.m_MouseKeyboard_LeftButtonMousePress;
        public InputActionMap Get() { return m_Wrapper.m_MouseKeyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseKeyboardActions set) { return set.Get(); }
        public void SetCallbacks(IMouseKeyboardActions instance)
        {
            if (m_Wrapper.m_MouseKeyboardActionsCallbackInterface != null)
            {
                @LeftButtonMousePress.started -= m_Wrapper.m_MouseKeyboardActionsCallbackInterface.OnLeftButtonMousePress;
                @LeftButtonMousePress.performed -= m_Wrapper.m_MouseKeyboardActionsCallbackInterface.OnLeftButtonMousePress;
                @LeftButtonMousePress.canceled -= m_Wrapper.m_MouseKeyboardActionsCallbackInterface.OnLeftButtonMousePress;
            }
            m_Wrapper.m_MouseKeyboardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftButtonMousePress.started += instance.OnLeftButtonMousePress;
                @LeftButtonMousePress.performed += instance.OnLeftButtonMousePress;
                @LeftButtonMousePress.canceled += instance.OnLeftButtonMousePress;
            }
        }
    }
    public MouseKeyboardActions @MouseKeyboard => new MouseKeyboardActions(this);

    // TochScreen
    private readonly InputActionMap m_TochScreen;
    private ITochScreenActions m_TochScreenActionsCallbackInterface;
    private readonly InputAction m_TochScreen_SingleTouch;
    private readonly InputAction m_TochScreen_MultiTouch;
    public struct TochScreenActions
    {
        private @InputControls m_Wrapper;
        public TochScreenActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SingleTouch => m_Wrapper.m_TochScreen_SingleTouch;
        public InputAction @MultiTouch => m_Wrapper.m_TochScreen_MultiTouch;
        public InputActionMap Get() { return m_Wrapper.m_TochScreen; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TochScreenActions set) { return set.Get(); }
        public void SetCallbacks(ITochScreenActions instance)
        {
            if (m_Wrapper.m_TochScreenActionsCallbackInterface != null)
            {
                @SingleTouch.started -= m_Wrapper.m_TochScreenActionsCallbackInterface.OnSingleTouch;
                @SingleTouch.performed -= m_Wrapper.m_TochScreenActionsCallbackInterface.OnSingleTouch;
                @SingleTouch.canceled -= m_Wrapper.m_TochScreenActionsCallbackInterface.OnSingleTouch;
                @MultiTouch.started -= m_Wrapper.m_TochScreenActionsCallbackInterface.OnMultiTouch;
                @MultiTouch.performed -= m_Wrapper.m_TochScreenActionsCallbackInterface.OnMultiTouch;
                @MultiTouch.canceled -= m_Wrapper.m_TochScreenActionsCallbackInterface.OnMultiTouch;
            }
            m_Wrapper.m_TochScreenActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SingleTouch.started += instance.OnSingleTouch;
                @SingleTouch.performed += instance.OnSingleTouch;
                @SingleTouch.canceled += instance.OnSingleTouch;
                @MultiTouch.started += instance.OnMultiTouch;
                @MultiTouch.performed += instance.OnMultiTouch;
                @MultiTouch.canceled += instance.OnMultiTouch;
            }
        }
    }
    public TochScreenActions @TochScreen => new TochScreenActions(this);
    public interface IMouseKeyboardActions
    {
        void OnLeftButtonMousePress(InputAction.CallbackContext context);
    }
    public interface ITochScreenActions
    {
        void OnSingleTouch(InputAction.CallbackContext context);
        void OnMultiTouch(InputAction.CallbackContext context);
    }
}
